spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password: '{cipher}27c4d5e57bef5baf0d50bce5ca12e4bab301a1130d047ee0bad3e8615876a8e8'
token:
  expiration_time: 86400000
  secret: X0JpgxoT9X0kbkkK3oQe+01qfWqPazy8iVFjIa/C7smYXlHiXie77Rk7gdVzq515959+3QodcuHIsKixyxyLbA==
gateway:
  ip: localhost
