server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  profiles:
    active: native #native or git
  cloud:
    config:
      server:
        native:
          search-location: file:///C:\Users\magna\Desktop\study\Spring-Cloud-Study
        git:
          uri: https://github.com/black-pepper/Spring-Cloud-Study.git
          username: black-pepper
          password: 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
#          uri: file:///C:\Users\magna\Desktop\study\Spring-Cloud-Study

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh